### PR TITLE
fprettify

### PR DESCRIPTION
**Pull request by sseraj**
## Purpose

Formatting the Fortran code with fprettify

## Expected time until merged

1 week

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing

Current test pass

## Checklist

- [x] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [x] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by sseraj** [comment]
Verified that the fprettify check fails without formatting and outputs which files need to be formatted

**Comment by akleb** [comment]
Why not stick with the two space tab?

**Comment by sseraj** [comment]
Previously, we had an initial 2 space tab and then 3 space tabs after that. We decided to use a 4 space tab to be consistent with our Python formattingn

**Comment by sseraj** [comment]
Verified that a single file failure also fails the job

**Review by nwu63 — APPROVED** [review]

**Review by akleb — APPROVED** [review]

**Pull request merged**
