### PR TITLE
Update numpy dependency

### PR DESCRIPTION
**Pull request by A-CGray**
## Purpose

pyspline doesn't currently work with any numpy past 1.21 due to f2py issues, this PR reflects this in the installation requirements

## Expected time until merged

1 hour

## Type of change

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Checklist

- [ ] I have run `flake8` and `black` to make sure the Python code adheres to PEP-8 and is consistently formatted
- [ ] I have formatted the Fortran code with `fprettify` or C/C++ code with `clang-format` as applicable
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Review by marcomangano — APPROVED** [review]

**Comment by sseraj** [comment]
pySpline works fine with NumPy 1.24 on the Ubuntu images. It fails to build on the CentOS image because that image has GCC 4.8.5, which is very old. We can fix this by passing the `-std=c99` flag. See this issue for details: https://github.com/numpy/numpy/issues/22572.

**Comment by A-CGray** [comment]
> pySpline works fine with NumPy 1.24 on the Ubuntu images. It fails to build on the CentOS image because that image has GCC 4.8.5, which is very old. We can fix this by passing the `-std=c99` flag. See this issue for details: [numpy/numpy#22572](https://github.com/numpy/numpy/issues/22572).

ok, are you gonna open a PR to fix that?

**Comment by eirikurj** [comment]
I can add this to the already open [PR fixing the compiler inconsistency](https://github.com/mdolab/pyspline/pull/55/files).

**Comment by sseraj** [comment]
> I can add this to the already open PR #55 fixing the compiler inconsistency.

Thanks, I think that makes sense.

**Comment by eirikurj** [comment]
PR #55 now has the flags updated, should be good once tests pass (aside from the black failures)

**Comment by eirikurj** [comment]
Tests are failing due to black. PR #56 should be merged first.

**Comment by A-CGray** [comment]
@eirikurj am I understanding correctly that this PR is no longer required once https://github.com/mdolab/pyspline/pull/55 is merged?

**Comment by eirikurj** [comment]
Yes, #55 should take care of this. I dont think we need to add any restrictions on numpy, so we should close this one.

**Pull request closed without merging**
