### PR TITLE
Update testflo tests

### PR DESCRIPTION
**Pull request by nwu63**
## Purpose
I updated the testflo tests to use the new BaseRegTest API.
- reference files now use JSON
- tolerances are specified more succinctly
- renamed example files so testflo does not think they are tests

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- Maintenance

**The pull request will fail because the PR in baseclasses has not been merged. I will mark this as ready for review once that is merged.**

### CODE REVIEW

**Comment by joanibal** [comment]
It looks like something is going wrong with the JSON reader
```python
    with BaseRegTest(self.ref_file, train=False) as handler:

  File "/home/mdolabuser/repos/baseclasses/baseclasses/BaseRegTest.py", line 35, in __init__

    self.db = [float(val.rstrip()) for val in file_handle.readlines()]

  File "/home/mdolabuser/repos/baseclasses/baseclasses/BaseRegTest.py", line 35, in <listcomp>

    self.db = [float(val.rstrip()) for val in file_handle.readlines()]

ValueError: could not convert string to float: '{'


```

**Comment by nwu63** [comment]
The reason that one test failed is because that specific docker image does not contain the baseclasses PR that updated BaseRegTest, since the built bot failed last night so it didn't push the image. And the reason that image failed last night is due to unrelated issues with pyoptsparse and we can ignore it for now.

**Comment by nwu63** [comment]
The tests all pass now, after the images were re-built last night.

**Review by joanibal — APPROVED** [review]

**Review by bernardopacini — APPROVED** [review]
Looks good to me.

**Pull request merged**
